openapi: 3.0.0
info:
  version: 1.0.0
  title: FoodAdvice OpenAPI
  description: Retrieves food reviews
  contact:
    name: FoodAdvice
    url: https://fidilio.com/
    email: info@fidilio.com
servers:
  - url: https://server1.com
    description: development servers
  - url: https://server2.com
    description: backupserver
paths:
  /v1/restaurants/:
    get:
      parameters:
        - name: restaurants
          in: path
          description: retrieves names of restaurants
          required: true
          schema: 
            type: string
            minLength: 2
            maxLengt: 10
            example: Indian
      responses:
        "200":
          description: successful
          content: 
            application/jason:
  /v1/restaurants/{restaurantsID}:
    get:
    summary: restaurants Identification number
    description: retrieves a 4 digit code of restaurants
      parameters:
        - name: restaurants
          in: path
          required: true 
          schema:
            type: string
      responses:
        "200":
          description: successful
          content: 
            application/jason:
      

  


      

        

  
    
  

