openapi: 3.0.0
info:
  version: '1.0'
  title: makeUP
  description: 'Specification for OpenAPItest course'
  termsOfService: https://example.com/terms/ 
  contact:
     name: Maryam
     url: https://digiato.com/author/maryammousavi/
     email: mousavi.digiato@gmail.com
  license:
    name: Apache 2.0
    url:  https://www.apache.org/licenses/LICENSE-2.0.html
servers: 
  - url: http://dev.digiato.com 
    description: development server 
  - url: http://dev.zoomit.com
    description: backup server
paths:
  /v1/cosmetics:
    get:
      parameters:
        - name: cosmetics
          in: path
          required: true
          description: retrieves **cosmetics** 
          schema: 
      responses: 
          "200":
            description: list of cosmetics
            content:
              application/jason: 
                schema: 
                  type: array
                  minitems: 1
                  mazitems: 100
                  items:
                    type: string
                    description: cosmetcis names
                    minLength: 2
                    maxLength: 25
  /v1/user/:
    post:
      parameters:
        - name: user
          description: a newly added user
          in: path
          required: true
      responses:
        "201": 
          description: successfully created a user

  /v1/item/:
    put:



